[package]
name = "yakstack"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.3.4"

[profile.dev.package.godot]
hint-mostly-unused = true

[profile.release.package.godot]
hint-mostly-unused = true